// Generated by view binder compiler. Do not edit!
package com.example.klyuchnik.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.klyuchnik.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityDataViewBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button idBtnAddPerson;

  @NonNull
  public final Button idBtnReadPerson;

  @NonNull
  public final EditText idEdtAudienceNumber;

  @NonNull
  public final EditText idEdtCardNumber;

  @NonNull
  public final EditText idEdtFullName;

  @NonNull
  public final EditText idEdtTime;

  private ActivityDataViewBinding(@NonNull LinearLayout rootView, @NonNull Button idBtnAddPerson,
      @NonNull Button idBtnReadPerson, @NonNull EditText idEdtAudienceNumber,
      @NonNull EditText idEdtCardNumber, @NonNull EditText idEdtFullName,
      @NonNull EditText idEdtTime) {
    this.rootView = rootView;
    this.idBtnAddPerson = idBtnAddPerson;
    this.idBtnReadPerson = idBtnReadPerson;
    this.idEdtAudienceNumber = idEdtAudienceNumber;
    this.idEdtCardNumber = idEdtCardNumber;
    this.idEdtFullName = idEdtFullName;
    this.idEdtTime = idEdtTime;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityDataViewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityDataViewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_data_view, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityDataViewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.idBtnAddPerson;
      Button idBtnAddPerson = ViewBindings.findChildViewById(rootView, id);
      if (idBtnAddPerson == null) {
        break missingId;
      }

      id = R.id.idBtnReadPerson;
      Button idBtnReadPerson = ViewBindings.findChildViewById(rootView, id);
      if (idBtnReadPerson == null) {
        break missingId;
      }

      id = R.id.idEdtAudienceNumber;
      EditText idEdtAudienceNumber = ViewBindings.findChildViewById(rootView, id);
      if (idEdtAudienceNumber == null) {
        break missingId;
      }

      id = R.id.idEdtCardNumber;
      EditText idEdtCardNumber = ViewBindings.findChildViewById(rootView, id);
      if (idEdtCardNumber == null) {
        break missingId;
      }

      id = R.id.idEdtFullName;
      EditText idEdtFullName = ViewBindings.findChildViewById(rootView, id);
      if (idEdtFullName == null) {
        break missingId;
      }

      id = R.id.idEdtTime;
      EditText idEdtTime = ViewBindings.findChildViewById(rootView, id);
      if (idEdtTime == null) {
        break missingId;
      }

      return new ActivityDataViewBinding((LinearLayout) rootView, idBtnAddPerson, idBtnReadPerson,
          idEdtAudienceNumber, idEdtCardNumber, idEdtFullName, idEdtTime);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
